
ARDMK_DIR=/usr/share/arduino

ARDUINO_DIR=/home/s100/soft/arduino-1.8.19
AVR_TOOLS_DIR=$(ARDUINO_DIR)/hardware/tools/avr

BOARD_TAG=uno
# MONITOR_PORT=/dev/ttyACM0
MONITOR_PORT=/dev/narval_motors

include $(ARDMK_DIR)/Arduino.mk
